#!/usr/bin/env bash

# Immediately catch all errors
set -eo pipefail

# Uncomment for debugging
# set -x
# env

# Autogenerate mtrrc
cat << 'EOF' > ~/.mtrrc
# ~/.mtrrc: autogenerated via dev container lifecycle scripts
# see .devcontainer/post-create-command.sh (in the microntracker-ros repo)
# MANUAL CHANGES ARE NOT PERSISTENT

# Enable autocomplete using colcon
. /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

# Set ENABLE_RGL based on NVIDIA environment variables
# Some hybrid graphic laptops require the following settings to offload graphics rendering task to NVIDIA and load the GLX library
if [ -n "$NVIDIA_VISIBLE_DEVICES" ] && [ -n "$(echo $NVIDIA_DRIVER_CAPABILITIES | grep -e graphics -e all )" ]; then
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export ENABLE_RGL=true
else
    export ENABLE_RGL=false
fi

# Aliases for manging workspace
alias bows='$OVERLAY_WS/src/microntracker-ros/.devcontainer/update-content-command.sh'
alias cows='cd $OVERLAY_WS'
alias sows='source $OVERLAY_WS/install/setup.bash'
alias srws='source /opt/ros/$ROS_DISTRO/setup.bash'

EOF

# Check if ~/.bashrc is patched, otherwise apply it
if [ ! -f ~/.bashrc ] || ! grep -q 'mtrrc' ~/.bashrc; then
    cp /etc/skel/.bashrc ~/
    cat << 'EOF' >> ~/.bashrc

# Source autogenerated mtrrc
. ~/.mtrrc
EOF
fi
